matrix:
  include:
    - name: "Linux Swift 4.1.3"
      os: linux
      language: generic
      dist: trusty
      sudo: required
      env:
        - SWIFT_BRANCH=swift-4.1.3-release
        - SWIFT_VERSION=swift-4.1.3-RELEASE
      install:
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar -xz -C swift
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"

    - name: "Linux Swift 4.2.3"
      os: linux
      language: generic
      dist: trusty
      sudo: required
      env:
        - SWIFT_BRANCH=swift-4.2.3-release
        - SWIFT_VERSION=swift-4.2.3-RELEASE
      install:
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar -xz -C swift
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"

    - name: "Linux Swift 5.0"
      os: linux
      language: generic
      dist: trusty
      sudo: required
      env:
        - SWIFT_BRANCH=swift-5.0-release
        - SWIFT_VERSION=swift-5.0-RELEASE
      install:
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar -xz -C swift
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"

    - name: "macOS Xcode 9.4"
      os: osx
      osx_image: xcode9.4
      language: generic
      sudo: required

    - name: "macOS Xcode 10.2"
      os: osx
      osx_image: xcode10.2
      language: generic
      sudo: required
      install: 
        - gem install xcpretty-travis-formatter
      script:
        - xcodebuild test -scheme FootlessParser | xcpretty -f `xcpretty-travis-formatter`
        - pod repo update --silent; pod lib lint --allow-warnings

script:
  - swift --version
  - swift package reset
  - swift build
  - swift test
